# Generated by Django 4.2.4 on 2023-09-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamplatform',
            options={'ordering': ['name', 'about', 'website']},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='core.streamplatform'),
            preserve_default=False,
        ),
    ]
